dataset_name : '100118_fixedhead/train'
dataset_type : 'gaze'
tfrecord_name : 'train.tfrecords'
# Train targets are taken from image filenames
filename_regex : '(\d.\d+)_(\d.\d+).png'
full_dataset: True
shuffle : True
buffer_size : 64
batch_size : 16
# Image augmentation when training
image_augmentation : True
# Brightness Augmentation
random_brigtness : True
brightnes_max_delta : 0.1
# Contrast Augmentation
random_contrast : True
contrast_lower : 0.01
contrast_upper : 0.2
