dataset_name : '100118_fixedhead/test'
dataset_type : 'gaze'
tfrecord_name : 'test.tfrecords'
# Train targets are taken from image filenames
filename_regex : '(\d.\d+)_(\d.\d+).png'
full_dataset: False
dataset_len : 20
shuffle : False
batch_size : 20
# Image augmentation when training
image_augmentation : False