# Experiment name is the root directory for logs
experiment_name : 'estimator_gaze'
# Dataset parameters
train_dataset_yaml : 'datasets/synthetic_gaze_train_full.yaml'
test_dataset_yaml : 'datasets/synthetic_gaze_test.yaml'
# Summary and Checkpoint saving
save_summary_steps : 1
save_checkpoints_steps : 1
# Training parameters
num_epochs : 30
# Early stopping
max_loss : 500
best_loss : 500
patience : 5
# Model parameters
model_func: 'resnet_gaze_model_fn'
model_params:
  model_name : 'gaze_resnet'
  # Optimization parameters
  optimizer_type : 'adam'
  learning_rate : 0.001
  # Model parameters - Resnet Base
  num_rb : 2
  rb_feat : 16
  rb_kernel : 3
  batch_norm : True
  # Model parameters - FC Head
  fc_layers : [64, 32]
  dimred_feat : 16
  dimred_kernel : 4
  dimred_stride : 2
  dropout_keep_prob: 0.6





