# Device index of camera
video_source : 0
# Number of worker threads
num_workers : 2
# Size of the image queue
queue_size : 5
# Name of opencv window
window_name : "Gaze Tracker"
# Name of directory (in model directories) that contains the model checkpoint
ckpt_dir: "gaze_resnet_rb_kernel_3_fc_layers_64_batch_norm_False_dimred_stride_4_rb_feat_8_num_rb_2_dimred_feat_32_dimred_kernel_4_learning_rate_0.01"