dataset_name : '150118_gaze/train'
dataset_type : 'gaze'
tfrecord_name : 'test.tfrecords'
# Train targets are taken from image filenames
filename_regex : '(\d.\d+)_(\d.\d+).png'
full_dataset: True
shuffle : False
batch_size : 8
# Image augmentation when testing
image_augmentation : False