dataset_name : '100118_fixedhead/train'
dataset_type : 'gaze'
tfrecord_name : 'small_synthetic.tfrecords'
# Train targets are taken from image filenames
filename_regex : '(\d.\d+)_(\d.\d+).png'
dataset_len : 500
shuffle : True
buffer_size : 16
batch_size : 8
# Image augmentation when training
image_augmentation : False

