model_func: 'resnet_gaze_model_fn'
model_name : 'gaze_resnet'
# Optimization parameters
optimizer_type : 'adam'
dropout_keep_prob: 0.5
learning_rate : 0.0001
batch_norm : False
hyperparams:
  # Resnet Base
  num_rb : [2, 3]
  rb_feat : [16, 32]
  rb_kernel : [3, 6]
  # FC Head
  fc_layers : [[64], [32], [128]]
  dimred_feat : [16, 32, 64]
  dimred_kernel : [4, 6, 8]
  dimred_stride : [2, 4]
# Parameters required by the model_func
model_params: ['model_name', 'dropout_keep_prob', 'optimizer_type', 'learning_rate', 'num_rb', 'rb_feat', 'rb_kernel', 'batch_norm', 'fc_layers', 'dimred_feat', 'dimred_kernel', 'dimred_stride']
